# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        our_db_provider:
            entity:
                class: AppBundle:Usuario
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # activate different ways to authenticate
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: /evento/login
                check_path: /evento/login
            logout:
                path:   /logout
                target: /

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

    access_control:
        - { path: ^/evento/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/evento, roles: ROLE_USER }
        - { path: ^/evento/new, roles: ROLE_ADMIN }
